#!/bin/sh
# Runs after files are removed: deregister the ubus object and refresh LuCI menu
[ -n "${IPKG_INSTROOT}" ] && exit 0
/etc/init.d/rpcd restart 2>/dev/null
rm -f /tmp/luci-indexcache* 2>/dev/null
rm -rf /tmp/luci-modulecache 2>/dev/null
exit 0
